### PR TITLE
Add bytecodevtab subspec

### PR DESCRIPTION
**Pull request by Kudo**
Adding `bytecodevtab` subspec for [The Bytecode() And Tables_Used() Table-Valued Functions](https://www.sqlite.org/bytecodevtab.html) support

### CODE REVIEW

**Comment by clemensg** [comment]
Thanks!

**Comment by Kudo** [comment]
thanks for merging this pr!

**Comment by Kudo** [comment]
@clemensg any chances for publishing the update to cocoapods registry? sqlite 3.45.2 was also released about one month ago. it would be good to have these updates. thanks!

**Comment by simolus3** [comment]
I have just published a version for sqlite 3.45.3, but since I was the only one publishing the recent updates, I've missed this PR and didn't pull it into my local checkout. Apologies! I have followed up with version `3.45.3+1` on Cocoapods which contains the bytecodevtab subspec.

**Comment by Kudo** [comment]
awesome. `3.45.3+1` works great for me, thanks @simolus3!

**Pull request merged**
