### PR TITLE
Upgrade to sqlite3 version `3.39.4`

### PR DESCRIPTION
**Pull request by simolus3**

### CODE REVIEW

**Comment by clemensg** [comment]
@simolus3  Thanks. I am currently having problems pushing the new version and not enough time to debug it currently. It might be related to me using macOS 13 as build host. If you want, I can add you as second owner to the CocoaPods project and give you access to this repo. Then you can take over when I don't have enough time ;)

**Comment by simolus3** [comment]
Hi. Sure, feel free to add me (oss@simonbinder.eu) and I'll try to build and push the current version.

**Comment by clemensg** [comment]
Hi, great, I added you here as collaborator and to CocoaPods Trunk.

**Comment by simolus3** [comment]
Thanks. I've pushed the release and tagged it in Git.

**Pull request merged**
